databases:
- name: nerdfight-db
  region: ohio
  plan: standard

services:
- type: web
  name: nerdfight.online
  env: static
  rootDir: site
  buildCommand: hugo --gc --minify
  staticPublishPath: public
  domains:
    - nerdfight.online
  routes:
    - type: rewrite
      source: /* # rewrite everything we don't provide to the GTS instance
      destination: https://gts.nerdfight.online:80/
- type: web
  name: ack.nerdfight.online
  env: docker
  plan: standard
  region: ohio
  dockerfilePath: ./Dockerfile.akkoma
  autoDeploy: false
  envVars:
    - key: DB_HOST
      fromDatabase:
        name: nerdfight-db
        property: host
    - key: DB_USER
      fromDatabase:
        name: nerdfight-db
        property: user
    - key: DB_PASSWORD
      fromDatabase:
        name: nerdfight-db
        property: password
