databases:
- name: nerdfight-db
  region: ohio
  plan: standard

services:
- type: web
  name: nerdfight.online
  env: static
  rootDir: site
  buildCommand: hugo --gc --minify
  staticPublishPath: public
  domains:
    - nerdfight.online
  routes:
    - type: rewrite
      source: /.well-known/*
      destination: https://ack.nerdfight.online/.well-known/*
- type: web
  name: ack.nerdfight.online
  env: docker
  plan: standard
  region: ohio
  rootDir: akkoma
  dockerfilePath: ./Dockerfile
  domains:
    - ack.nerdfight.online
  autoDeploy: false
  envVars:
    - key: DB_HOST
      fromDatabase:
        name: nerdfight-db
        property: host
    - key: DB_USER
      fromDatabase:
        name: nerdfight-db
        property: user
    - key: DB_PASSWORD
      fromDatabase:
        name: nerdfight-db
        property: password
    - key: DOMAIN
      value: ack.nerdfight.online
    - key: STATIC_DOMAIN
      value: nerdfight.online
 - type: cron
   name: mills_lane.nerdfight.online
   env: docker
   plan: starter
   rootDir: mills_lane
   dockerfilePath: ./Dockerfile
   schedule: "0 13 * * 5" # friday at 8am EST
   envVars:
    - key: DB_HOST
      fromDatabase:
        name: nerdfight-db
        property: host
    - key: DB_USER
      fromDatabase:
        name: nerdfight-db
        property: user
    - key: DB_PASSWORD
      fromDatabase:
        name: nerdfight-db
        property: password
    - fromGroup: nerdfight-mills-lane

