title = "Nerdfight Online"
baseURL = "https://nerdfight.online"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Nerdfight Online"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Tamarou LLC"
  favicon = ""
  site_logo = ""
  description = "Real Nerds Fake Fighting with GIFs"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  recent_posts_number = 5
  show_reading_time = true

[[params.ananke_socials]]
name = "mastodon"
url = "https://ack.nerdfight.online"
