---
name: Reporting Service Issue
description: There is a partial or full outage on Nerdfight Online
labels:
  - Reporting Service Issue
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to let us know you're experiencing a problem with the site!

        Please make sure there are not other submissions for the same service interruption.

        If this is a new issue, please briefly describe what you are seeing in the title.
  - type: textarea
    attributes:
      label: |
        Please describe the issue you are seeing.
      description: |
        Use as much detail as possible.
      value: |
        A couple questions to help you get started:
        1. Are you seeing error codes? If so please include the full error message and,
        if it makes sense to, a screenshot.
        2. When are you seeing the issue? When you are submitting posts? Uploading media?
        3. Is the issue only happening in certain circumstances?
           For example, only for uploading certain file sizes, or only when using a specific
           browser / 3rd party app. If so,  please include which and what versions.

        Please note that if there are issues with individual apps or with Mastodon core that
        we can work with you to determine that to be the case, but we can not fix third party apps
        and do not directly contribute to the Mastodon project at this time.
    validations:
      required: true
  - type: input
    attributes:
      label: How long have you noticed this issue?
      description: |
        Approximately how long have you been experiencing this issue?
    validations:
      required: true
  - type: input
    attributes:
      label: What geographic region are you accessing Hachyderm from?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there anything else that we should know?
    validations:
      required: false

